version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: user-api
    tty: true
    image: app/api
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PROFILE=dev
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    links:
      - db

  db:
    container_name: db
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: db_pgadmin
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_USER_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - '9119:80'
    depends_on:
      - db