version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: user-api
    tty: true
    image: app/api
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/test_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PROFILE=dev
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
    links:
      - db

  db:
    container_name: db
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db

  pgadmin:
    container_name: db_pgadmin
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '9119:80'
    depends_on:
      - db